import type { Baseplaat, Fineer, HPL, Bewerking, StaffelRegel, Instelling, Orderlijst, OrderlijstRegel, Order } from './types'

// ─── Baseplaten ────────────────────────────────────────────────────────────────
export const seedBaseplaten: Baseplaat[] = [
  {
    id: 'bp-1',
    naam: 'MDF',
    dikte_mm: 12,
    breedte_mm: 1220,
    lengte_mm: 2440,
    prijs_per_m2: 18.50,
    beschikbaar: true,
  },
  {
    id: 'bp-2',
    naam: 'MDF',
    dikte_mm: 18,
    breedte_mm: 1220,
    lengte_mm: 2440,
    prijs_per_m2: 24.00,
    beschikbaar: true,
  },
  {
    id: 'bp-3',
    naam: 'Multiplex',
    dikte_mm: 15,
    breedte_mm: 1220,
    lengte_mm: 2440,
    prijs_per_m2: 32.00,
    beschikbaar: true,
  },
  {
    id: 'bp-4',
    naam: 'Multiplex',
    dikte_mm: 18,
    breedte_mm: 1220,
    lengte_mm: 2440,
    prijs_per_m2: 38.50,
    beschikbaar: true,
  },
  {
    id: 'bp-5',
    naam: 'MDF Groot',
    dikte_mm: 18,
    breedte_mm: 1220,
    lengte_mm: 3050,
    prijs_per_m2: 26.00,
    beschikbaar: true,
  },
]

// ─── Fineers ───────────────────────────────────────────────────────────────────
export const seedFineers: Fineer[] = [
  {
    id: 'fn-1',
    naam: 'Okoumé',
    prijs_voorzijde_lang: 12.50,
    prijs_voorzijde_kort: 14.00,
    prijs_tegenzijde_lang: 8.00,
    prijs_tegenzijde_kort: 9.50,
    voegmethodes: ['gestolpt', 'geschoven', 'mixmatch', 'gedraaid_geschoven'],
    voeg_standaard: 'gestolpt',
    fk_advies: 'fabriek',
    info: 'Afrikaans hout, licht roodbruin, goed bewerkbaar.',
    status_lang: 'beschikbaar',
    status_kort: 'beschikbaar',
    gallery_foto_url: undefined,
  },
  {
    id: 'fn-2',
    naam: 'Mahonie',
    prijs_voorzijde_lang: 18.00,
    prijs_voorzijde_kort: 20.00,
    prijs_tegenzijde_lang: 11.00,
    prijs_tegenzijde_kort: 13.00,
    voegmethodes: ['gestolpt', 'geschoven', 'gedraaid_geschoven'],
    voeg_standaard: 'geschoven',
    fk_advies: 'foto_kuiper',
    info: 'Klassiek interieurhout, warme rode tint.',
    status_lang: 'beschikbaar',
    status_kort: 'tijdelijk_niet',
    gallery_foto_url: undefined,
  },
  {
    id: 'fn-3',
    naam: 'Berken',
    prijs_voorzijde_lang: 10.00,
    prijs_voorzijde_kort: 11.50,
    prijs_tegenzijde_lang: 7.00,
    prijs_tegenzijde_kort: 8.00,
    voegmethodes: ['gestolpt', 'geschoven', 'mixmatch'],
    voeg_standaard: 'gestolpt',
    fk_advies: 'fabriek',
    info: 'Licht hout met fijne nerf, populair voor modern interieur.',
    status_lang: 'beschikbaar',
    status_kort: 'beschikbaar',
    gallery_foto_url: undefined,
  },
  {
    id: 'fn-4',
    naam: 'Eik',
    prijs_voorzijde_lang: 22.00,
    prijs_voorzijde_kort: 25.00,
    prijs_tegenzijde_lang: 14.00,
    prijs_tegenzijde_kort: 16.00,
    voegmethodes: ['gestolpt', 'geschoven', 'mixmatch', 'gedraaid_geschoven'],
    voeg_standaard: 'geschoven',
    fk_advies: 'persoonlijk',
    info: 'Tijdloos eikenhout, uitgesproken nerf, meerdere kwaliteiten.',
    status_lang: 'beschikbaar',
    status_kort: 'beschikbaar',
    gallery_foto_url: undefined,
  },
  {
    id: 'fn-5',
    naam: 'Teak',
    prijs_voorzijde_lang: 35.00,
    prijs_voorzijde_kort: 40.00,
    prijs_tegenzijde_lang: 22.00,
    prijs_tegenzijde_kort: 26.00,
    voegmethodes: ['gestolpt', 'geschoven'],
    voeg_standaard: 'gestolpt',
    fk_advies: 'foto_klant',
    info: 'Exotisch hout, goudbruin van kleur, duurzame kwaliteit.',
    status_lang: 'beschikbaar',
    status_kort: 'niet_beschikbaar',
    gallery_foto_url: undefined,
  },
]

// ─── HPL ───────────────────────────────────────────────────────────────────────
export const seedHPL: HPL[] = [
  {
    id: 'hpl-1',
    kleur: 'Wit (U1101)',
    prijs_lang: 28.00,
    prijs_kort: 32.00,
    hpl_afm_lang_b: 1310,
    hpl_afm_lang_l: 2800,
    hpl_afm_kort_b: 1310,
    hpl_afm_kort_l: 1300,
    info: 'Standaard wit HPL, glad oppervlak.',
    status_lang: 'beschikbaar',
    status_kort: 'beschikbaar',
    gallery_foto_url: undefined,
  },
  {
    id: 'hpl-2',
    kleur: 'Antraciet (U961)',
    prijs_lang: 32.00,
    prijs_kort: 36.00,
    hpl_afm_lang_b: 1310,
    hpl_afm_lang_l: 2800,
    hpl_afm_kort_b: 1310,
    hpl_afm_kort_l: 1300,
    info: 'Donker antraciet HPL, modern uitstraling.',
    status_lang: 'beschikbaar',
    status_kort: 'beschikbaar',
    gallery_foto_url: undefined,
  },
  {
    id: 'hpl-3',
    kleur: 'Lichtgrijs (U763)',
    prijs_lang: 30.00,
    prijs_kort: 34.00,
    hpl_afm_lang_b: 1310,
    hpl_afm_lang_l: 2800,
    hpl_afm_kort_b: 1310,
    hpl_afm_kort_l: 1300,
    info: 'Neutraal lichtgrijs, veelzijdig inzetbaar.',
    status_lang: 'beschikbaar',
    status_kort: 'tijdelijk_niet',
    gallery_foto_url: undefined,
  },
  {
    id: 'hpl-4',
    kleur: 'Eiken decor (D3436)',
    prijs_lang: 38.00,
    prijs_kort: 43.00,
    hpl_afm_lang_b: 1310,
    hpl_afm_lang_l: 2800,
    hpl_afm_kort_b: 1310,
    hpl_afm_kort_l: 1300,
    info: 'Houtdecor eiken, structuur oppervlak.',
    status_lang: 'beschikbaar',
    status_kort: 'beschikbaar',
    gallery_foto_url: undefined,
  },
]

// ─── Bewerkingen ───────────────────────────────────────────────────────────────
export const seedBewerkingen: Bewerking[] = [
  {
    id: 'bw-1',
    naam: 'Zaagwerk',
    beschrijving: 'Plaat op maat gezaagd. Netto maat: breedte −10mm × lengte −20mm.',
    prijs: 3.50,
    compatibiliteit: ['kaal', 'fineer', 'hpl'],
    beschikbaar: true,
    standaard_geselecteerd: true,
    volgorde: 1,
  },
  {
    id: 'bw-2',
    naam: 'Schuurwerk',
    beschrijving: 'Fijn schuren van het oppervlak voor een gladde afwerking.',
    prijs: 2.00,
    compatibiliteit: ['kaal', 'fineer'],
    beschikbaar: true,
    standaard_geselecteerd: true,
    volgorde: 2,
  },
  {
    id: 'bw-3',
    naam: 'Grunderen',
    beschrijving: 'Voorzien van een grondlaag voor betere verfhechting.',
    prijs: 4.50,
    compatibiliteit: ['kaal'],
    beschikbaar: true,
    standaard_geselecteerd: false,
    volgorde: 3,
  },
  {
    id: 'bw-4',
    naam: 'Kantenbanden',
    beschrijving: 'ABS kantenbanden rondom aangebracht.',
    prijs: 5.00,
    compatibiliteit: ['kaal', 'hpl'],
    beschikbaar: true,
    standaard_geselecteerd: false,
    volgorde: 4,
  },
]

// ─── Staffel ───────────────────────────────────────────────────────────────────
export const seedStaffelFineerHPL: StaffelRegel[] = [
  { id: 'sf-1', van_aantal: 1, tot_aantal: 9, multiplier: 1.0 },
  { id: 'sf-2', van_aantal: 10, tot_aantal: 24, multiplier: 0.95 },
  { id: 'sf-3', van_aantal: 25, tot_aantal: 49, multiplier: 0.90 },
  { id: 'sf-4', van_aantal: 50, tot_aantal: null, multiplier: 0.85 },
]

export const seedStaffelKaal: StaffelRegel[] = [
  { id: 'sk-1', van_aantal: 1, tot_aantal: 9, multiplier: 1.0 },
  { id: 'sk-2', van_aantal: 10, tot_aantal: 24, multiplier: 0.97 },
  { id: 'sk-3', van_aantal: 25, tot_aantal: 49, multiplier: 0.94 },
  { id: 'sk-4', van_aantal: 50, tot_aantal: null, multiplier: 0.90 },
]

// ─── Instellingen ──────────────────────────────────────────────────────────────
export const seedInstellingen: Instelling[] = [
  { sleutel: 'verzend_drempel', waarde: '1750' },
  { sleutel: 'verzend_kosten', waarde: '25' },
  { sleutel: 'btw_percentage', waarde: '21' },
  { sleutel: 'bedrijf_naam', waarde: 'Kuiper Holland B.V.' },
  { sleutel: 'bedrijf_email', waarde: 'info@kuiperholland.nl' },
]

// ─── Demo Orderlijsten ─────────────────────────────────────────────────────────
export const seedOrderlijsten: Orderlijst[] = [
  {
    id: 'ol-1',
    user_id: 'demo-user',
    naam: 'Project Keuken Renovatie',
    status: 'actueel',
    aangemaakt_op: '2026-04-15T09:00:00Z',
    bijgewerkt_op: '2026-05-01T14:30:00Z',
  },
  {
    id: 'ol-2',
    user_id: 'demo-user',
    naam: 'Slaapkamer Kastenwand',
    status: 'concept',
    aangemaakt_op: '2026-04-20T11:00:00Z',
    bijgewerkt_op: '2026-04-28T16:00:00Z',
  },
  {
    id: 'ol-3',
    user_id: 'demo-user',
    naam: 'Woonkamer Wandpanelen',
    status: 'verstuurd',
    aangemaakt_op: '2026-03-10T08:00:00Z',
    bijgewerkt_op: '2026-03-18T10:00:00Z',
  },
]

// ─── Demo Regels ───────────────────────────────────────────────────────────────
export const seedOrderlijstRegels: OrderlijstRegel[] = [
  {
    id: 'or-1',
    orderlijst_id: 'ol-1',
    basisplaat_id: 'bp-2',
    categorie: 'fineer',
    fineer_voor: 'fn-4',
    fineer_tegen: 'fn-3',
    voegmethode: 'geschoven',
    bewerkingen: ['bw-1'],
    ruimte_indeling: 'geen',
    aantal: 24,
    prijs_per_stuk: 87.50,
    totaal_prijs: 2100.00,
  },
  {
    id: 'or-2',
    orderlijst_id: 'ol-1',
    basisplaat_id: 'bp-1',
    categorie: 'kaal',
    bewerkingen: ['bw-4'],
    ruimte_indeling: 'per_ruimte',
    ruimtes: [
      { naam: 'Keuken', aantal: 8, afwerking: 'blankwerk' },
      { naam: 'Bijkeuken', aantal: 4, afwerking: 'donker_gebeitst' },
    ],
    aantal: 12,
    prijs_per_stuk: 32.00,
    totaal_prijs: 384.00,
  },
]

// ─── Demo Orders ───────────────────────────────────────────────────────────────
export const seedOrders: Order[] = [
  {
    id: 'ord-1',
    user_id: 'demo-user',
    ordernummer: 'KH-2026-0042',
    status: 'in_productie',
    track_trace: undefined,
    verwachte_levering: '2026-05-20',
    totaal: 3480.00,
    bevestigd_op: '2026-04-28T10:00:00Z',
  },
  {
    id: 'ord-2',
    user_id: 'demo-user',
    ordernummer: 'KH-2026-0031',
    status: 'verzonden',
    track_trace: 'PostNL:3SPAR123456789',
    verwachte_levering: '2026-05-10',
    totaal: 1875.50,
    bevestigd_op: '2026-04-10T14:00:00Z',
  },
  {
    id: 'ord-3',
    user_id: 'demo-user',
    ordernummer: 'KH-2026-0018',
    status: 'geleverd',
    track_trace: 'PostNL:3SPAR987654321',
    verwachte_levering: '2026-04-02',
    totaal: 920.00,
    bevestigd_op: '2026-03-22T09:00:00Z',
  },
]
